# Generated by Django 4.2.30 on 2026-08-22 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Filing',
            fields=[
                ('filing_uid', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('filing_type', models.CharField(max_length=100)),
                ('filed_on', models.DateField()),
                ('source_registry', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='IngestionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_file', models.CharField(max_length=255)),
                ('line_number', models.PositiveIntegerField()),
                ('record_type', models.CharField(max_length=64)),
                ('raw_payload', models.JSONField()),
                ('status', models.CharField(choices=[('accepted', 'Accepted'), ('coerced', 'Coerced'), ('quarantined', 'Quarantined'), ('rejected', 'Rejected')], max_length=16)),
                ('reason', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='LegalEntity',
            fields=[
                ('entity_uid', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('legal_name', models.TextField()),
                ('legal_name_ar', models.TextField(blank=True, null=True)),
                ('jurisdiction', models.CharField(max_length=2)),
                ('registration_no', models.CharField(max_length=100)),
                ('incorporation_date', models.DateField()),
                ('status', models.CharField(max_length=50)),
                ('status_as_of', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='NaturalPerson',
            fields=[
                ('person_uid', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('full_name', models.TextField()),
                ('full_name_ar', models.TextField(blank=True, null=True)),
                ('nationality', models.CharField(max_length=2)),
                ('dob_year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='OwnershipInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bps', models.IntegerField()),
                ('valid_from', models.DateField()),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('filing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ownership_interests', to='registry.filing')),
                ('held_entity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ownership_interests', to='registry.legalentity')),
                ('holder_entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='held_ownership_interests', to='registry.legalentity')),
                ('holder_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ownership_interests', to='registry.naturalperson')),
                ('provenance', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='ownership_interest', to='registry.ingestionrecord')),
            ],
        ),
        migrations.AddConstraint(
            model_name='ingestionrecord',
            constraint=models.UniqueConstraint(fields=('source_file', 'line_number'), name='unique_ingestion_source_line'),
        ),
        migrations.AddField(
            model_name='filing',
            name='asserts_about',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='filings', to='registry.legalentity'),
        ),
        migrations.AddField(
            model_name='filing',
            name='supersedes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='superseded_by', to='registry.filing'),
        ),
        migrations.AddConstraint(
            model_name='ownershipinterest',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('holder_entity__isnull', True), ('holder_person__isnull', False)), models.Q(('holder_entity__isnull', False), ('holder_person__isnull', True)), _connector='OR'), name='ownership_has_exactly_one_holder'),
        ),
    ]
